from __future__ import annotations

import importlib.util
import os
import subprocess
import sys
from pathlib import Path
from typing import Any

from cfd_agent.tools.file_tool import project_root, write_json


REQUIRED_PACKAGES = {
    "pydantic": "pydantic",
    "jinja2": "jinja2",
    "ansys-fluent-core": "ansys.fluent.core",
    "h5py": "h5py",
}

DEFAULT_KEYS = {
    "SOLIDWORKS_ENABLED": "true",
    "SPACECLAIM_ENABLED": "true",
    "FLUENT_MESHING_ENABLED": "true",
    "FLUENT_SOLVER_ENABLED": "true",
    "CFD_AGENT_FOREGROUND": "true",
    "FLUENT_PROCESSOR_COUNT": "4",
    "ANSYS_VERSION": "221",
    "USE_PYFLUENT": "false",
}


def parse_env_file(path: str | Path) -> dict[str, str]:
    env_path = Path(path)
    if not env_path.is_file():
        return {}
    values: dict[str, str] = {}
    for raw_line in env_path.read_text(encoding="utf-8").splitlines():
        line = raw_line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        key, value = line.split("=", 1)
        values[key.strip()] = value.strip().strip('"')
    return values


def load_project_env(root: str | Path | None = None) -> dict[str, str]:
    base = Path(root) if root is not None else project_root()
    values = parse_env_file(base / ".env")
    loaded: dict[str, str] = {}
    for key, value in values.items():
        os.environ.setdefault(key, value)
        loaded[key] = os.environ.get(key, value)
    return loaded


def build_env_payload(config: dict[str, Any] | None = None) -> dict[str, str]:
    config = config or {}
    payload = dict(DEFAULT_KEYS)
    payload["SOLIDWORKS_ENABLED"] = _bool_text(config.get("solidworks_enabled", True))
    payload["SPACECLAIM_ENABLED"] = _bool_text(config.get("spaceclaim_enabled", True))
    payload["FLUENT_MESHING_ENABLED"] = _bool_text(config.get("fluent_meshing_enabled", True))
    payload["FLUENT_SOLVER_ENABLED"] = _bool_text(config.get("fluent_solver_enabled", True))
    payload["CFD_AGENT_FOREGROUND"] = _bool_text(config.get("foreground", True))
    payload["SPACECLAIM_EXECUTABLE"] = _resolve_configured_path(
        config.get("spaceclaim_executable"),
        _spaceclaim_candidates(),
        r"D:/Program Files/ANSYS Inc/v221/scdm/SpaceClaim.exe",
    )
    payload["FLUENT_EXECUTABLE"] = _resolve_configured_path(
        config.get("fluent_executable"),
        _fluent_candidates(),
        r"D:/Program Files/ANSYS Inc/v221/fluent/ntbin/win64/fluent.exe",
    )
    return payload


def write_project_env(config: dict[str, Any] | None = None, root: str | Path | None = None) -> Path:
    base = Path(root) if root is not None else project_root()
    values = build_env_payload(config)
    lines = ["# Generated by CFD Agent one-click deployment", *[f"{key}={value}" for key, value in values.items()]]
    env_file = base / ".env"
    env_file.write_text("\n".join(lines) + "\n", encoding="utf-8")
    return env_file


def deployment_check(root: str | Path | None = None, config: dict[str, Any] | None = None) -> dict[str, Any]:
    base = Path(root) if root is not None else project_root()
    env_values = {**parse_env_file(base / ".env"), **build_env_payload(config)}
    checks = {
        "python_dependencies": _dependency_check(),
        "solidworks": {
            "ok": env_values.get("SOLIDWORKS_ENABLED", "").lower() == "true",
            "path": env_values.get("SOLIDWORKS_EXECUTABLE"),
            "message": "SolidWorks COM will be used when SOLIDWORKS_ENABLED=true.",
        },
        "spaceclaim": _executable_check(env_values.get("SPACECLAIM_EXECUTABLE"), _spaceclaim_candidates()),
        "fluent": _executable_check(env_values.get("FLUENT_EXECUTABLE"), _fluent_candidates()),
        "foreground": {
            "ok": env_values.get("CFD_AGENT_FOREGROUND", "true").lower() == "true",
            "value": env_values.get("CFD_AGENT_FOREGROUND", "true"),
        },
    }
    report = {
        "ok": all(check.get("ok", False) for check in checks.values()),
        "env_file": str((base / ".env").resolve()),
        "checks": checks,
        "recommended_env": env_values,
    }
    output = base / "outputs" / "deployment_check"
    write_json(output / "environment_check.json", report)
    (output / "environment_check.md").write_text(_markdown_report(report), encoding="utf-8")
    return report


def software_smoke_check(root: str | Path | None = None, config: dict[str, Any] | None = None, timeout: int = 60) -> dict[str, Any]:
    base = Path(root) if root is not None else project_root()
    env_values = {**parse_env_file(base / ".env"), **build_env_payload(config)}
    output = base / "outputs" / "deployment_check"
    output.mkdir(parents=True, exist_ok=True)
    checks = {
        "solidworks": _solidworks_smoke_check(output, timeout) if env_values.get("SOLIDWORKS_ENABLED", "true").lower() == "true" else _disabled_check(output / "solidworks_smoke.log"),
        "spaceclaim": _spaceclaim_smoke_check(env_values.get("SPACECLAIM_EXECUTABLE"), output, timeout),
        "fluent_meshing": _fluent_smoke_check(env_values.get("FLUENT_EXECUTABLE"), output, timeout, meshing=True),
        "fluent_solver": _fluent_smoke_check(env_values.get("FLUENT_EXECUTABLE"), output, timeout, meshing=False),
    }
    report = {
        "ok": all(check.get("ok", False) for check in checks.values()),
        "checks": checks,
    }
    write_json(output / "software_smoke_check.json", report)
    (output / "software_smoke_check.md").write_text(_smoke_markdown_report(report), encoding="utf-8")
    return report


def _bool_text(value: Any) -> str:
    return "true" if bool(value) else "false"


def _resolve_configured_path(value: Any, candidates: list[Path], fallback: str) -> str:
    if value:
        path = Path(str(value)).expanduser()
        return str(path.resolve()) if path.exists() else str(path)
    for candidate in candidates:
        if candidate.exists():
            return str(candidate.resolve())
    return fallback


def _executable_check(value: str | None, candidates: list[Path]) -> dict[str, Any]:
    path = Path(value).expanduser() if value else None
    found = path if path and path.is_file() else next((candidate for candidate in candidates if candidate.is_file()), None)
    return {
        "ok": found is not None,
        "path": str(found.resolve()) if found else (str(path) if path else None),
        "message": "Executable found." if found else "Executable not found; set the path manually.",
    }


def _dependency_check() -> dict[str, Any]:
    packages = {
        name: importlib.util.find_spec(module) is not None
        for name, module in REQUIRED_PACKAGES.items()
    }
    return {
        "ok": all(packages.values()),
        "packages": packages,
        "message": "Python dependencies are installed." if all(packages.values()) else "Run py -m pip install -r requirements.txt.",
    }


def _disabled_check(log_file: Path) -> dict[str, Any]:
    log_file.write_text("Smoke check skipped because this tool is disabled in .env.\n", encoding="utf-8")
    return {"ok": True, "skipped": True, "message": "Disabled in .env.", "log_file": str(log_file)}


def _solidworks_smoke_check(output: Path, timeout: int) -> dict[str, Any]:
    log_file = output / "solidworks_smoke.log"
    script = (
        "import win32com.client\n"
        "app = win32com.client.Dispatch('SldWorks.Application')\n"
        "app.Visible = True\n"
        "print('SolidWorks COM OK')\n"
    )
    return _run_python_smoke("solidworks", script, output, log_file, timeout)


def _spaceclaim_smoke_check(executable: str | None, output: Path, timeout: int) -> dict[str, Any]:
    log_file = output / "spaceclaim_smoke.log"
    marker = output / "spaceclaim_smoke_marker.txt"
    script_file = output / "spaceclaim_smoke.py"
    script_file.write_text(
        "import clr\n"
        "clr.AddReference('System')\n"
        "from System.IO import File\n"
        f"File.WriteAllText(r'{_escape_path(marker)}', 'SpaceClaim smoke OK')\n",
        encoding="utf-8",
    )
    path = Path(executable).expanduser() if executable else None
    if not path or not path.is_file():
        return _missing_executable("SpaceClaim", executable, log_file)
    command = [
        str(path),
        "/Splash=False",
        "/Welcome=False",
        f"/RunScript={script_file.resolve()}",
        "/ScriptAPI=22",
        "/ExitAfterScript=True",
    ]
    result = _run_process(command, output, log_file, timeout)
    if result["ok"] and not marker.is_file():
        result["ok"] = False
        result["message"] = "SpaceClaim started but did not write the smoke marker."
    return result


def _fluent_smoke_check(executable: str | None, output: Path, timeout: int, meshing: bool) -> dict[str, Any]:
    name = "fluent_meshing" if meshing else "fluent_solver"
    log_file = output / f"{name}_smoke.log"
    journal = output / f"{name}_smoke.jou"
    journal.write_text("/exit yes\n", encoding="utf-8")
    path = Path(executable).expanduser() if executable else None
    if not path or not path.is_file():
        return _missing_executable("Fluent", executable, log_file)
    command = [str(path), "3d", "-t1", "-i", str(journal.resolve())]
    if meshing:
        command.insert(2, "-meshing")
    else:
        command.insert(2, "-r")
        command.insert(3, "22.1.0")
    return _run_process(command, output, log_file, timeout)


def _run_python_smoke(name: str, script: str, output: Path, log_file: Path, timeout: int) -> dict[str, Any]:
    script_file = output / f"{name}_smoke.py"
    script_file.write_text(script, encoding="utf-8")
    return _run_process([sys.executable, str(script_file.resolve())], output, log_file, timeout)


def _run_process(command: list[str], cwd: Path, log_file: Path, timeout: int) -> dict[str, Any]:
    try:
        completed = subprocess.run(command, cwd=cwd, text=True, capture_output=True, timeout=timeout, check=False)
    except subprocess.TimeoutExpired as exc:
        log_file.write_text((exc.stdout or "") + "\n" + (exc.stderr or "") + f"\nTimed out after {timeout} seconds.\n", encoding="utf-8")
        return {"ok": False, "message": f"Timed out after {timeout} seconds.", "command": command, "log_file": str(log_file)}
    except OSError as exc:
        log_file.write_text(str(exc), encoding="utf-8")
        return {"ok": False, "message": f"Launch failed: {exc}", "command": command, "log_file": str(log_file)}
    log_file.write_text((completed.stdout or "") + "\n" + (completed.stderr or ""), encoding="utf-8")
    return {
        "ok": completed.returncode == 0,
        "message": "Smoke check passed." if completed.returncode == 0 else f"Process returned exit code {completed.returncode}.",
        "command": command,
        "returncode": completed.returncode,
        "log_file": str(log_file),
    }


def _missing_executable(name: str, executable: str | None, log_file: Path) -> dict[str, Any]:
    message = f"{name} executable not found: {executable or '<empty>'}"
    log_file.write_text(message + "\n", encoding="utf-8")
    return {"ok": False, "message": message, "path": executable, "log_file": str(log_file)}


def _escape_path(path: Path) -> str:
    return str(path.resolve()).replace("\\", "\\\\")
    return {
        "ok": all(packages.values()),
        "packages": packages,
        "message": "Python dependencies are installed." if all(packages.values()) else "Run py -m pip install -r requirements.txt.",
    }


def _spaceclaim_candidates() -> list[Path]:
    return [
        Path(r"D:/Program Files/ANSYS Inc/v221/scdm/SpaceClaim.exe"),
        Path(r"C:/Program Files/ANSYS Inc/v221/scdm/SpaceClaim.exe"),
        Path(r"D:/Program Files/ANSYS Inc/v222/scdm/SpaceClaim.exe"),
        Path(r"C:/Program Files/ANSYS Inc/v222/scdm/SpaceClaim.exe"),
    ]


def _fluent_candidates() -> list[Path]:
    return [
        Path(r"D:/Program Files/ANSYS Inc/v221/fluent/ntbin/win64/fluent.exe"),
        Path(r"C:/Program Files/ANSYS Inc/v221/fluent/ntbin/win64/fluent.exe"),
        Path(r"D:/Program Files/ANSYS Inc/v222/fluent/ntbin/win64/fluent.exe"),
        Path(r"C:/Program Files/ANSYS Inc/v222/fluent/ntbin/win64/fluent.exe"),
    ]


def _markdown_report(report: dict[str, Any]) -> str:
    lines = ["# CFD Agent Deployment Check", "", f"Overall: {'OK' if report['ok'] else 'Needs attention'}", ""]
    for name, check in report["checks"].items():
        lines.append(f"- {name}: {'OK' if check.get('ok') else 'Missing'}")
        if check.get("path"):
            lines.append(f"  Path: `{check['path']}`")
        if check.get("message"):
            lines.append(f"  Note: {check['message']}")
    return "\n".join(lines) + "\n"


def _smoke_markdown_report(report: dict[str, Any]) -> str:
    lines = ["# CFD Agent Software Smoke Check", "", f"Overall: {'OK' if report['ok'] else 'Needs attention'}", ""]
    for name, check in report["checks"].items():
        lines.append(f"- {name}: {'OK' if check.get('ok') else 'Failed'}")
        lines.append(f"  Note: {check.get('message', '')}")
        if check.get("log_file"):
            lines.append(f"  Log: `{check['log_file']}`")
    return "\n".join(lines) + "\n"
