from enum import Enum


class WorkflowState(str, Enum):
    CREATED = "CREATED"
    VALIDATED = "VALIDATED"
    SOLIDWORKS_MODEL_CREATED = "SOLIDWORKS_MODEL_CREATED"
    SPACECLAIM_DOMAIN_CREATED = "SPACECLAIM_DOMAIN_CREATED"
    FLUENT_MESH_CREATED = "FLUENT_MESH_CREATED"
    CASE_CREATED = "CASE_CREATED"
    SOLVER_RUNNING = "SOLVER_RUNNING"
    SOLVER_COMPLETED = "SOLVER_COMPLETED"
    POSTPROCESSED = "POSTPROCESSED"
    REPORT_CREATED = "REPORT_CREATED"
    FAILED = "FAILED"
